openapi: "3.0.1"
info:
  title: "SCALE Commercial Agreements Service Event Defintions"
  version: v0.0.9
  description: This shows how to define data driven specification for an event for a given Commercial Agreement and Lot. (EOI,RFI, RFP, DA .....)
#  PLACEHOLDERs - to be uncommented when implemented
  termsOfService: "http://api.crowncommercial.gov.uk/terms/"
  contact:
    email: "apiteam@crowncommercial.gov.uk"
  license:
    name: "Open Government Licence 3.0"
    url: "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
#
#
#security:
#  - OAuth2:
#    - read
tags:
- name: Event Definition
  description: "EventDefinitions"
  externalDocs:
    description: "Find out more"
    url: "http://apis.crowncommercial.gov.uk"

paths:
  # Mock endpoint
  /event-definition:
    get:
      summary: Mock Endpoint 
      description:  Mock Endpoint to define structure of 
      tags:
      - Event Definition
      operationId: get-agreements
      
      responses:
        '200':
          description: Collection of Commercial Agreement summary entities
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/EventDefinition'
        

 
components:


#  securitySchemes:
#    OAuth2:
#      type: oauth2
#      flows:
#        authorizationCode:
#          authorizationUrl: http://ccsexample.com/oauth/auth
#          tokenUrl: https://api.crowncommercial.gov.uk/oauth/token
#          scopes:
#            read: Grants read access
#           only read for MVP
  schemas:
#

    EventDefinition:
        type: array
        items:
          allOf:
            - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/cat/CaT-service.yaml#/components/schemas/EvalCriteria'
            - type: object
              properties:
                relatesTo:
                  type: string
                relateItems:
                  type: string
                requirementGroups:
                  allOf:
                    - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/cat/CaT-service.yaml#/components/schemas/QuestionGroup'
                    - type: object
                      properties:
                        OCDS:
                          type: object
                          properties:
                            requirements:
                              type: array
                              items:
                                $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/cat/CaT-service.yaml#/components/schemas/Question'

#
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/davejhughes/agreement-service/v0.0.6
