openapi: 3.0.1
info:
  title: SCALE Commercial Agreements Service
  version: "0.0.1"
  description: This API allows access to CCS Commercial Agreement data. This is used both to provide information to users and to govern the behaviour of other systems for example 'Buy a Thing' and 'Contract for a Thing', where processes may differ based on the configuration of the underlying Commercial Agreement and Lot.  

# Some data is explicitly omitted from the initial version of the API. Some detailed notes below but a summary here
# - Terms and conditions are not included (in MVP) as individual data items. It is assumed that a link to a t&cs document will be provided for all Agreements. To be considered post MVP.
# - 'Special Considerations' - mentioned in an email from JW, needs analysis
# - ...
# References: TDDA-009 - Agreements Service (https://docs.google.com/document/d/1PkS669G7cinFkvNI3OpxUyjoYxVWhkzYRkrTByDfRaY)
#
# TODO:
# 1. calls to manage data e.g. POST agreement, lot; PUT modifications and so on

servers:
# This is NOT a real server
- url: https://crowncommercialservices.gov.uk/dummy/scale/agreements
tags:
- name: agreements
paths:

  # No filter parameter included against API principle due to no use case for this call for MVP which would require a filter and enterprise search provides search functionality on agreements.
  /agreements:
    get:
      summary: Returns an array of all configured Commercial Agreements
      description: Returns an array of Commercial Agreement Ids, names and simple descriptions
      tags:
      - agreements
      operationId: get-agreements
      responses:
        200:
          description: Collection of Commercial Agreement summary entities
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/AgreementSummary'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
  
  /agreements/{ca-number}:
    get:
      summary: Returns details of the specified Commercial Agreement
      description: Returns the definition of the specified Commercial Agreement
      tags:
      - agreements
      operationId: get-agreement-detail
      parameters:
        - name: ca-number
          in: path
          description: Commercial Agreement unique 'number' e.g. "RM1045"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Commercial Agreement detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgreementDetail'
        404:
          description: Commercial Agreement not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
 
 # The get-agreement-detail call explicitly omits CPV codes in the initial version. These will be added later if required. As there are potentially thousands of CPV codes it was felt that these would overwhelm the output and management of the underlying data.  Additional calls can be added to provide these if required in a similar way to the '/agreements/{ca-number}/updates' call below.
 
  
  /agreements/{ca-number}/lots/{lot-number}:
    get:
      summary: Returns details of the specified Lot for this Commercial Agreement
      description: Returns data about the Lot, both general information and parameters required to govern the behaviour of applications using this data
      tags:
      - agreements
      operationId: get-lot-details
      parameters:
        - name: ca-number
          in: path
          description: Commercial Agreement unique number e.g. "RM1045"
          required: true
          schema:
            type: string
        - name: lot-number
          in: path
          description: Unique number of Lot within Commercial Agreement
          required: true
          schema:
            type: string
      responses:
        200:
          description: Lot details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LotDetail'
        404:
          description: Commercial Agreement and/or Lot not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'

  
  /agreements/{ca-number}/updates:
    get:
      summary: Returns any updates added to the Agreement
      description: Returns updates recorded for the specified Commercial Agreement
      tags:
      - agreements
      operationId: get-agreement-updates
      parameters:
        - name: ca-number
          in: path
          description: Commercial Agreement unique number e.g. "RM1045"
          required: true
          schema:
            type: string
      responses:
        200:
          description: Commercial Agreement updates
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/AgreementUpdate'
        404:
          description: Commercial Agreement not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'



components:
  schemas:

    AgreementSummary:
      type: object
      properties:
        number:
          type: string
          description: Commercial Agreement Number e.g. "RM1045"
        name:
          type: string
          description: Commercial Agreement Name e.g. "Linen and Laundry Services"
          
          
# Agreement Detail omits some Agreement data in the initial version.
#  - Suppliers will be shown at a Lot level rather than Agreement level
#  - CPV codes are omitted as noted above

    AgreementDetail:
      type: object
      properties:
        number:
          type: string
          description: Commercial Agreement Number e.g. "RM1045"
        name:
          type: string
          description: Commercial Agreement Name e.g. "Linen and Laundry Services"
        description:
          type: string
          description: Short textual description of the commercial agreement
        startDate:
          type: string
          format: date
          description: Effective start date of Commercial Agreement
        endDate:
          type: string
          format: date
          description: Effective start date of Commercial Agreement
        detailUrl:
          type: string
          format: uri
          description: URL of the Agreement detail page on the CCS website
        sectors:
          type: array
          items:
            type: string
            description: A sector permitted to buy using the Agreement 
        benefits:
          type: array
          items:
            type: string
            description: short description of the benefit
        lots:
          type: array
          items:
            $ref: '#/components/schemas/LotSummary'
        documents:
          type: array
          items:
            $ref: '#/components/schemas/Document'

    LotDetail:
      type: object
      properties:
        number:
          type: string
          description: Lot number e.g. "1" for Lot 1
        name:
          type: string
          description: Lot name e.g. "Finance"
        description:
          type: string
          description: Short textual description of the Lot
        type:
          type: string
          enum: [product|service|product and service]
        minimumValue:
          type: number
          format: float
          description: The minimum value for which this Lot applies
        maximumValue:
          type: number
          format: float
          description: The maximum value for which this Lot applies
        location:
          # Need to understand what this is used for and how this is used to build it out
          type: string
          description: PLACEHOLDER. Needs to be an anyOf for National:Regional or individual Regions or even lowest level NUTS2
        minContractLength:
          type: object
          properties:
            unit:
              type: string
              enum: [day|month|year]
              description: The unit of the length value
            length:
              type: integer
              format: int64
              description: The number of units
        maxContractLength:
          type: object
          properties:
            unit:
              type: string
              enum: [day|month|year]
              description: The unit of the length value
            length:
              type: integer
              format: int64
              description: The number of units
        minQuantity:
          type: object
          properties:
            unit:
              type: string
              description: The unit of the quantity value
            length:
              type: number
              format: float
              description: The number of units
        maxQuantity:
          type: object
          properties:
            unit:
              type: string
              description: The unit of the quantity value
            length:
              type: number
              format: float
              description: The number of units
        services:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: The name of the Service
              description:
                type: string
                description: Brief description of the Service
        products:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
                description: The name of the Product
              description:
                type: string
                description: Brief description of the Product
        suppliers:
          type: array
          description: Suppliers registered against this Lot
          items:
            $ref: '#/components/schemas/Organisation'
        buyingMethods:
          type: object
          properties:
            allowsDirectAward: 
              type: boolean
              description: Does the Lot allow Direct Award?
            allowsFurtherCompetition:
              type: boolean
              description: Does the Lot allow Further Competition?
            allowsMarketplace:
              type: boolean
              description: Is the Lot a product based Marketplace? 
            allowsEAuction:
              type: boolean
              description: Is the lot for eAuctions?
        buyingSystemURL:
          type: string
          format: uri
          description: The URL to use for the system to progress the procurement (e.g. BaT, CaT, other)
        termsAndConditions:
          $ref: '#/components/schemas/Document'
        documents:
          # An array to hold 'other documents'.  Later versions of the API can add attributes for links to specific documents
          type: array
          items:
            $ref: '#/components/schemas/Document'
        buyerNeeds:
          # Lot default text for buyer needs for CaT
          type: array
          items:
            $ref: '#/components/schemas/BuyerNeed'
        # Further to the rules model below can data drive the whole rules evaluation triggering the rules from events in CaT and BaT
        # e.g. a list of events mapped to rules in config. When event happens, if Agreement has rule data then we evaluate the rule. All in a standard function passed event data and Agreement data
        # Assumption that event mapping discussed above is required for MVP
        rules:
          type: array
          items:
                $ref: '#/components/schemas/LotRule'
    
    LotRule:
        # Rules such as 'Prices may not rise more than {x} times in any consecutive {y} day period' can be included in the 'other' element - in this case 2 data-points would be required.
        # In the above example:
        #  name="max number of prices rises in period"
        #  ruleId="maxNumberPriceChangesInPeriod"
        #  lotAttributes=[ {"numberOfTimes","integer",,3,}, 
        #                  {"daysInPeriod" ,"integer",,7,}]
        #  transactionData= ["priceRisesLastPeriod","product.priceRises"]
        #  evaluationType="complex"
        #  as here specific logic is required to obtain the number of price rises before evaluating
      type: object
      properties:
        name:
          type: string
          description: Name of the rule (3 or 4 word description)
        ruleId: 
          type: string
          description: Unique identifier of the rule
        lotAttributes:
          type: array
          items:
            $ref: '#/components/schemas/NameValueType'
        transactionData:
          type: array
          description: Data required from the relevant transaction to be able to evaluate the rule
          items:
            type: object
            properties:
              name:
                type: "string"
                description: name of the variable
              location:
                type: "string"
                description: Path or other location of the data which can be evaluated by the application
        evaluationType:
          type: string
          enum: [equal , greater, less, complex]
          # regexp requires the expression. Left for post-MVP
          # complex will require specific code to evaluate e.g. 'identify number of price rises in n days'
        
    
    NameValueType:
      type: object
      properties:
        name: 
          type: string
          description: The name of the 'other' bound to be used as hashmap key
        datatype:
        # decided not to use date as this would actually be duration and that's an integer
          type: string
          enum: [string|integer|number]
          description: the datatype of the 'other' lotBound value
        valueText: 
          type: string
        valueInteger:
          type: integer
        valueNumber:
          type: number


    AgreementUpdate:
      type: object
      properties:
        updateDate:
          type: string
          format: date
          description: Date that the update was added
        updateLink:
          type: string
          format: uri
          description: Link to further information regarding the update
        updateText:
          type: string
          description: Actual update text

    LotSummary:
      type: object
      properties:
        number:
          type: string
          description: Lot number e.g. "1" for Lot 1
        name:
          type: string
          description: Lot name e.g. "Finance"

          
    Document:
      type: object
      properties:
        documentUri:
          type: string
          format: uri
        documentName:
          type: string
        documentVersion:
          type: string
        

    Organisation:
      type: object
      properties:
        organisationId:
          type: string
          description: Conclave Organisation Id
        organisationName:
          type: string
          description: Company name
        contactName:
          type: string
          description: Contact name for this context
        contactEmail:
          type: string
          format: email

    BuyerNeed:
      type: object
      properties:
        needId:
          type: integer
          format: int64
          description: Id of the need (to allow alignment with CaT)
        needName:
          type: string
          description: Name of Buyer Need
        needText:
          type: string
          description: Text to be displayed for Buyer need

    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    Error:
      type: object
      properties:
        status:
          type: string
        title:
          type: string
        detail:
          type: string
