openapi: 3.0.1
info:
  title: SCALE Guided Match Decision Tree Service API
  version: "0.0.11.PT"
servers:
  - url: https://{apiHost}{basePath}
    description: "Server base URL - parameterised for different environments"
    variables:
      apiHost:
        default: czuhfg17q4.execute-api.eu-west-2.amazonaws.com
        description: API Host. Default is SCALE DEV, subject to change and downtime.
      basePath:
        default: /dev/scale/decision-tree
        description: Decision Tree API base path. Default is DEV path.
tags:
  - name: scale
paths:

  /journeys:
    get:
      tags:
      - search-journeys
      operationId: search-journeys
      parameters:
        - name: q
          in: query
          description: Journey search term
          required: true
          schema:
            type: string
      responses:
        200:
          description: Collection of journey entities, may be zero
          content:
            application/json:
              schema:
                type: array
                items:
                    $ref: '#/components/schemas/Journey'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'

  /journeys/{uuid}/questions/{question-uuid}:
    get:
      tags:
        - get-journey-question
      operationId: get-journey-question
      parameters:
        - name: uuid
          in: path
          description: Journey unique ID
          required: true
          schema:
            type: string
            format: uuid
        - name: question-uuid
          in: path
          description: Journey question unique ID
          required: true
          schema:
            type: string
            format: uuid
        - name: modifier
          in: query
          description: Term used as an additional key for Dynamic List question lookups
          required: false
          schema:
            type: string

      responses:
        200:
         description: A journey question entity
         content:
          application/json:
            schema:
              $ref: '#/components/schemas/Question'
        404:
          description: Journey-question entity not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'

  /journeys/{uuid}/questions/{question-uuid}/outcome:
    post:
      tags:
        - get-journey-question-outcome
      operationId: get-journey-question-outcome
      parameters:
        - name: uuid
          in: path
          description: Journey unique ID
          required: true
          schema:
            type: string
            format: uuid
        - name: question-uuid
          in: path
          description: Journey question unique ID
          required: true
          schema:
            type: string
            format: uuid
        - name: modifier
          in: query
          description: Term used to identify 'modifier' journeys to move to when generic questions are complete
          required: false
          schema:
            type: string
      requestBody:
        description: Object containing a collection of answer values
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QuestionAnswers'
      responses:
        200:
         description: A journey question outcome entity
         content:
          application/json:
            schema:
              $ref: '#/components/schemas/Outcome'
        404:
          description: Next question entity not found (end of journey)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'

components:
  schemas:

    Journey:
      type: object
      properties:
        uuid:
          type: string
          format: uuid
          description: Guided Match journey unique identifier
        name:
          type: string
          description: Short descriptive name e.g. "Laptops"
        questionUuid:
          type: string
          format: uuid
          description: UUID for the Guided Match journey opening question

    Question:
      type: object
      required:
        - uuid
        - text
        - type
      properties:
        uuid:
          type: string
          format: uuid
          description: Question unique identifier
        text:
          type: string
          description: 'Question text e.g. "How many laptops would you like to buy?"'
        hint:
          type: string
          description: Further descriptive text regarding the question
        type:
          type: string
          enum: [boolean, list, multiSelectList, number, textInput, conditionalNumericInput, date, dateRange, postcode, nuts]
        variableName:
          type: string
          description: short variable name used in the interface for FaT/BaT to define the data held in the answer e.g. budget, deliveryDate, organisation
        pattern:
          type: string
          description: Regex pattern for client-side validation of free text entry fields
        definedAnswers:
          type: array
          uniqueItems: true
          description: Ordered collection of defined answers (for radio and checkbox types)
          items:
            $ref: '#/components/schemas/DefinedAnswer'

    DefinedAnswer:
      type: object
      required:
        - uuid
        - text
        - order
      properties:
        uuid:
          type: string
          format: uuid
          description: Answer unique identifier
        text:
          type: string
          description: 'Answer text e.g. "< 100", "Education", "Yes", "No"'
        order:
          type: integer
          description: Suggested order in which the answer should appear in a UI for a particular question
        hint:
          type: string
          description: Further descriptive text regarding the answer e.g. 'High value matters'
        conditionalInput:
          type: object
          description: Prototype. Conditional question definition
          properties:
            text:
              type: string
              description: Question text e.g. "How much is your budget?"
            hint:
              type: string
              description: question hint text e.g. "An estimate is fine"
        mutex:
          type: boolean
          description: Mutual exclusion indiciator. Answer should be separated by 'Or' in UI and when clicked, deselect any previously selected answers above

    QuestionAnswers:
      type: object
      description: Container for answer values to a particular question (UUIDs, free-text, date range etc).
      properties:
        data:
          type: array
          uniqueItems: true
          items:
            $ref: '#/components/schemas/GivenAnswer'

    GivenAnswer:
      type: object
      description: |
        Prototype. Container to facilitate conditional input question types.
        A GivenAnswer may consist of a uuid (boolean, list, multiSelectList), a value (number, textInput) or both (conditionalNumericInput)
      properties:
        uuid:
          type: string
          format: uuid
          description: Answer unique identifier
        value:
          type: string
          description: Text or numberic input value

    Lot:
      type: object
      required:
        - uuid
        - agreementName
        - scale
        - type
      properties:
        uuid:
          type: string
          format: uuid
          description: Lot unique identifier
        agreementName:
          type: string
          description: Commercial agreement name e.g. Workplace Services (FM Marketplace Phase 2)
        lotName:
          type: string
          description: Lot name (e.g. Lot 1b)
        agreementDescription:
          type: string
        lotDescription:
          type: string
        scale:
          type: boolean
          description: Whether this agreement is on the SCALE platform
        agreementId:
          type: string
        type:
          type: string
          enum: ['bat', 'cat', 'other', 'support']
          description: Primary purchasing route (Buy-a-Thing, Contract-a-Thing, general marketplace, contact CCS support)
        routeToMarket:
          type: string
          enum: ['fc','da']
          description: Route to market sub-type (Further Competition or Direct Award)
        url:
          type: string
          description: Jump off link to start procurement / go to marketplace

    Outcome:
      type: object
      description: |
        Represents the outcome to the submission of answer(s) to a particular question.
        This could be dynamic i.e. a subsequent question or single/multiple agreement lots,
        or the support type indicating that no matching agreement could be found
      required:
        - type
      properties:
        type:
          type: string
          enum: [lot, support, question]
        data:
          description: Present when type is 'lot' or 'question'
          oneOf:
            - type: array
              items:
                $ref: '#/components/schemas/Lot'
            - $ref: '#/components/schemas/Question'

    Errors:
      type: object
      properties:
        errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
    Error:
      type: object
      properties:
        status:
          type: string
        title:
          type: string
        detail:
          type: string
