openapi: "3.0.1"
info:
  title: "SCALE BaT Basket Service"
  version: v0.01
  description: This API provides access to the Buy a Thing shopping basket functionality. It includes functions to add and remove products from the basket, to save and restore the basket, to manage product wishists, to convert baskets to quotes (and quotes to baskets).
#  PLACEHOLDERs - to be uncommented when implemented
  termsOfService: "http://api.crowncommercial.gov.uk/terms/"
  contact:
    email: "apiteam@crowncommercial.gov.uk"
  license:
    name: "Open Government Licence 3.0"
    url: "https://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/"
#
# TODO:
# 1. Write the API
#
#security:
#  - OAuth2:
#    - read
tags:
- name: "Basket"
  description: "Operations on Active Basket"
  externalDocs:
    description: "Find out more"
    url: "http://apis.crowncommercial.gov.uk"
- name: "Saved Basket"
  description: "Operations on Saved Baskets"
  externalDocs:
    description: "Find out more"
    url: "http://apis.crowncommercial.gov.uk"
- name: "Wishlist"
  description: "Operations on Product wishlists"
  externalDocs:
    description: "Find out more"
    url: "http://apis.crowncommercial.gov.uk"
- name: "Quote"
  description: "Operations on Quotes"
  externalDocs:
    description: "Find out more"
    url: "http://apis.crowncommercial.gov.uk"
paths:
                
  /baskets:
    get:
      summary: Returns all Saved Baskets for the given scope (note not the current basket).
      description: Returns all Saved Baskets for the given scope - user, organisation, buyer group (note not the current basket).
      tags:
      - Saved Basket
      operationId: get-saved-basket-list
      parameters:
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-correlation-id'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-causation-id'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-channel'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-client'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/common/CCS_Standard_API_Params.yaml#/components/parameters/DetailParam'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/bat/bat-params.yaml#/components/parameters/OrderScopeParam'
      responses:
        200:
          description: Array of Saved Baskets for the specified scope ([user],Organisation,BuyerGroup)
          content:
            application/json:
              schema:
                type: "array"
                items:
                  oneOf:
                    - $ref: '#/components/schemas/SavedBasket'
                    - $ref: '#/components/schemas/SavedBasketSummary'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Schema.yaml#/components/schemas/Errors'

  /baskets/active:
    get:
      summary: Returns the Active Basket.
      description: Returns the contents of the current Basket for the signed in user (products, variants, quantities)
      tags:
      - Basket
      operationId: get-basket
      parameters:
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-correlation-id'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-causation-id'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-channel'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-client'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/common/CCS_Standard_API_Params.yaml#/components/parameters/DetailParam'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/bat/bat-params.yaml#/components/parameters/OrderScopeParam'
      responses:
        200:
          description: Details of the Active Basket
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Basket'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Schema.yaml#/components/schemas/Errors'
                
  /baskets/active/checkout:
    get:
      summary: Triggers the checkout process
      description: For the Active Basket starts a 'checkout' (and returns an array pf per supplier Orders to hand over to the BAT Orders API)
      tags:
      - Basket
      operationId: checkout-basket
      parameters:
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-correlation-id'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-causation-id'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-channel'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-client'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/common/CCS_Standard_API_Params.yaml#/components/parameters/DetailParam'
      responses:
        200:
          description: Order (in checkout process). One order returned per Supplier
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/bat/bat-schema.yaml#/components/schemas/SupplierOrder'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Schema.yaml#/components/schemas/Errors'
 
  /baskets/active/save:
    post:
      summary: Saves the active basket
      description: For the Active Basket saves it with the given name
      tags:
      - Basket
      operationId: save-basket
      parameters:
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-correlation-id'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-causation-id'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-channel'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-client'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/common/CCS_Standard_API_Params.yaml#/components/parameters/DetailParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SaveBasketParams'
      responses:
        200:
          description: Saved basket
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SavedBasket'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Schema.yaml#/components/schemas/Errors'

  /baskets/active/quote:
    post:
      summary: Creates quotes from the active basket
      description: Creates one quote per supplier from the active basket
      tags:
      - Basket
      operationId: save-as-quote
      parameters:
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-correlation-id'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-causation-id'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-channel'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Params.yaml#/components/parameters/x-client'
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/common/CCS_Standard_API_Params.yaml#/components/parameters/DetailParam'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateQuoteParams'
      responses:
        200:
          description: Quotes
          content:
            application/json:
              schema:
                type: "array"
                items:
                  $ref: '#/components/schemas/Quote'
        500:
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/CCS_Standard_API_Schema.yaml#/components/schemas/Errors'
                   
               
#
components:
#  securitySchemes:
#    OAuth2:
#      type: oauth2
#      flows:
#        authorizationCode:
#          authorizationUrl: http://ccsexample.com/oauth/auth
#          tokenUrl: https://api.crowncommercial.gov.uk/oauth/token
#          scopes:
#            read: Grants read access
#           only read for MVP
  schemas:
# TODO
# 1. remember to do oneOf for Detail/Summary for the depths of the Order object
    Basket:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/bat/bat-schema.yaml#/components/schemas/OrderBase'

    SavedBasket:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/bat/bat-schema.yaml#/components/schemas/OrderBase'
      type: object
      properties:
        name:
          type: string
          description: Name given to the basket when it was saved
          example: "Equipment for new starter"
        savedDate:
          type: string
          format: date-time
          example: "2020-12-25T17:32:28Z"
        shareLevel:
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/bat/bat-schema.yaml#/components/schemas/ShareScope'

    SavedBasketSummary:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/bat/bat-schema.yaml#/components/schemas/OrderBaseSummary'
      type: object
      properties:
        name:
          type: string
          description: Name given to the basket when it was saved
          example: "Equipment for new starter"
        savedDate:
          type: string
          format: date-time
          example: "2020-12-25T17:32:28Z"
        shareLevel:
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/bat/bat-schema.yaml#/components/schemas/ShareScope'


    SaveBasketParams:
      type: object
      properties:
        name:
          type: string
          description: The name of the saved Basket
          example: Standard Office Equipment
        shareLevel:
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/bat/bat-schema.yaml#/components/schemas/ShareScope'
  
    CreateQuoteParams:
      type: object
      properties:
        name:
          type: string
          description: The name of the Quote
          example: Standard Office Equipment
        shareLevel:
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/bat/bat-schema.yaml#/components/schemas/ShareScope'
        poNumber:
          type: string
          description: Purchase Order Number for the quote(s)
          example: PO453726218
  
    Quote:
      allOf:
        - $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/bat/bat-schema.yaml#/components/schemas/OrderBase'
      type: object
      properties:
        name:
          type: string
          description: the name of the quote
          example: R123436
        purchaseOrderNumber:
          type: string
          description: Buyer purchase order number
          example: PO1234
        shareLevel:
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/BAT_initial/bat/bat-schema.yaml#/components/schemas/ShareScope'
        supplierStatus:
          $ref: '#/components/schemas/QuoteSupplierStatus'
        buyerApprovalStatus:
          $ref: '#/components/schemas/QuoteBuyerStatus'
        
        
    QuoteSupplierStatus:
      type: object
      properties:
        status:
          description: The status of the quote (through the checkout/sales process)
          enum: [created,accepted,rejected]
        date:
          type: string
          format: date
          description: The date at which the quote was accepted/rejected by the supplier
          example: 2020-12-25
        supplierContact:
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/OCDS_Schema.yaml#/components/schemas/ContactPoint'

    QuoteBuyerStatus:
      type: object
      properties:
        status:
          description: The status of the quote (through the checkout/sales process)
          enum: [created,approved,rejected]
        date:
          type: string
          format: date
          description: The date at which the quote was approved/rejected by the buyer
          example: 2020-12-25
        buyerContact:
          $ref: 'https://raw.githubusercontent.com/Crown-Commercial-Service/ccs-scale-api-definitions/master/common/OCDS_Schema.yaml#/components/schemas/ContactPoint'


  ############## TO BE MOVED TO CENTRAL FILE ############


        
servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/davejhughes/BaT-Basket/v0.01